In [1]:
print("a")

a


merhaba 
açıklama eklenip, başka ifadelerde eklenebilir

__italik__

**kalın**

# En Büyük Başlık
## Merhaba
### Merhaba

# Neden NumPy ?

In [7]:
a = [1,2,3,4]
b = [2,3,4,5]


In [8]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
ab    

[2, 6, 12, 20]

In [9]:
import numpy as np     # numpy isleri kolaylastirir

In [12]:
a = np.array([1,2,3,4]) # numpy arrayler kullanilarak isler kolaylastirilir
b = np.array([2,3,4,5])

In [11]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i olusturmak

In [17]:
import numpy as np          # numpy kutuphane import edilir, kisayol olarak as ile np tanimlanir

In [18]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [23]:
a = np.array([1,2,3,4,5])

In [24]:
type(a) 

numpy.ndarray

In [26]:
np.array([3.14, 4, 2, 13], dtype="int") # dtype=" " ile istenilen veri formatinda tanimlama yapilabilr dtype="int", dtype="string"

array([ 3,  4,  2, 13])

In [27]:
np.array([3.14, 4, 2, 13], dtype="float")

array([ 3.14,  4.  ,  2.  , 13.  ])

In [29]:
np.array([3.14, 4, 2, 13], dtype="str")

array(['3.14', '4', '2', '13'], dtype='<U4')

In [30]:
#Sifirdan array olusturma

In [31]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.ones((3,5), dtype = int)  # 3 satir ve 5 sutunluk int degerleriyle olusturulan matris 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
np.full((3,5), 3)  # 3 lerden olusan bir matris

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [39]:
np.arange(0, 31, 3)  # tek bayutlu-satirli(vektor) matris 3 er artis ile matris olusturulur

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [40]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [41]:
np.random.normal(10,4, (3,4))  # cok bayutlu (matris) ort : 10, standartSapma= 4,  3'e 4'luk bir matris olusturulur

array([[17.17520629,  8.13289658, 13.14369266,  9.97161796],
       [11.83457995,  8.79099978, 12.41904404, 16.08754553],
       [ 9.27112125,  9.2985932 , 11.51095925, 12.15890807]])

In [42]:
np.random.normal(10,2, (3,4))  # cok bayutlu (matris) ort : 10, standartSapma= 2,  3'e 4'luk bir matris olusturulur

array([[10.7959492 , 14.13060406,  6.29219462, 10.04545092],
       [ 8.74751531, 11.1286532 , 11.84148371,  9.75192342],
       [10.61601883, 10.73566962,  9.2547177 ,  7.18064432]])

In [43]:
np.random.randint(0,10, (3,3))

array([[9, 4, 9],
       [5, 7, 1],
       [4, 8, 5]])

# NumPy Array Ozellikleri

* **ndim**  : boyut sayısı        ==> veri maddeleme tek yildiz(*)  kalın yazmak için iki yıldız(**)
* **shape** : _boyut_bilgisi_        ==> italik yazmak için alt tire baş ve sona eklenir  (_)
* **size**  : toplam eleman sayisi 
* **dtype** : array veri tipi

In [44]:
import numpy as np

In [45]:
np.random.randint(10, size = 10)  # random ifadelerden, random int degerker olusturur 

array([6, 4, 5, 8, 8, 8, 9, 0, 1, 4])

In [49]:
a = np.random.randint(10, size = 10)

In [47]:
a.ndim   # array'in boyut sayisi

1

In [48]:
a.shape  # array'in boyut bilgisini

(10,)

In [50]:
a.size  # toplam eleman sayisi

10

In [52]:
a.dtype # array veri tipi

dtype('int32')

In [53]:
b = np.random.randint(10, size = (3,5))

In [54]:
b

array([[7, 0, 5, 8, 1],
       [8, 5, 3, 3, 5],
       [6, 8, 6, 2, 3]])

In [55]:
b.ndim

2

In [56]:
b.shape

(3, 5)

In [58]:
b.size

15

In [59]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (reshaping)

In [2]:
import numpy as np

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
np.arange(1,10).reshape((3,3))  # 3 e 3 boyutlu array 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a = np.arange(1,10) # tek boyutlu bir matris, tek koseli parantez

In [25]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a.ndim

1

In [27]:
a.reshape((1,9))  # 2 boyutlu bir matrisdir ancak tek bir vetorun tasidigi bilgiyi tasir, [[]] iki koseli parantez

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [28]:
b = a.reshape((1,9))  # bir satir 9 sutundan olusan 2 boyutlu bir matris, reshape ile olusturulur.

In [29]:
b.ndim

2

# Array Birleştirme (Concatenation)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [4]:
np.concatenate([x,y])  # 2 array birlestirilir

array([1, 2, 3, 4, 5, 6])

In [6]:
z = np.array([7,8,9])

In [7]:
np.concatenate([x,y,z])  # 3 array birlestirilip

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#iki boyut

In [10]:
a = np.array([[1,2,3],[4,5,6]]) 

In [15]:
np.concatenate([a,a]) # satir duzeyinde birlestirme axis = 0 demek varsayilan degerdir

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
np.concatenate([a,a], axis = 1) # sutun duzeyinde birlestirme axis = 1

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [16]:
a = np.array([[1,2,3],[4,5,6]]) 

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

# Array Ayırma (Splitting)

In [60]:
import numpy as np

In [61]:
x = np.array([1,2,3,99,99,3,2,1])

In [63]:
np.split(x,[3,5]) # 3' e kadar olan kisim(1,2,3), 5'e kadar olan kisim (1,2,3,99,99) e kadar ksim (99,99) kalna kisim

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [64]:
a, b, c = np.split(x,[3,5])  # 3 kisma ayrilip a,b,c ye atanir ayni zamanda

In [65]:
a

array([1, 2, 3])

In [66]:
b

array([99, 99])

In [67]:
c

array([3, 2, 1])

In [68]:
# iki boyutlu ayırma

In [76]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [77]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [90]:
ust, alt = np.split(m,[2])

In [91]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [100]:
sol, sag = np.hsplit(m, [2])

In [101]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [102]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [103]:
import numpy as np

In [104]:
v = np.array([2,1,6,9,8])

In [105]:
v

array([2, 1, 6, 9, 8])

In [106]:
np.sort(v)

array([1, 2, 6, 8, 9])

In [107]:
v.sort()

In [108]:
v

array([1, 2, 6, 8, 9])

In [109]:
#iki bouytlu array siralama

In [113]:
np.random.normal(20,5, (3,3)) # oratalama 20, satandart sapma = 5  3X3 matris

array([[23.95654077, 24.27069247, 23.60330023],
       [26.76870429, 14.12337364, 19.49625163],
       [17.28296805, 21.55224031, 29.07269131]])

In [120]:
m = np.random.normal(20,5, (3,3)) # oratalama 20, satandart sapma = 5  3X3 matrisa 

In [125]:
m

array([[19.36149995, 20.18968111, 13.93750961],
       [24.26251149, 21.34175156, 17.18842985],
       [17.71963734, 21.73327628, 19.38814291]])

In [128]:
np.sort(m, axis = 1) #satirlari sıralar

array([[13.93750961, 19.36149995, 20.18968111],
       [17.18842985, 21.34175156, 24.26251149],
       [17.71963734, 19.38814291, 21.73327628]])

In [129]:
np.sort(m, axis = 0) # sutunları siralar

array([[17.71963734, 20.18968111, 13.93750961],
       [19.36149995, 21.34175156, 17.18842985],
       [24.26251149, 21.73327628, 19.38814291]])

In [131]:
5*np.array([1,2,7])

array([ 5, 10, 35])

In [144]:
np.random.randint(10, size = (4,8))  

array([[9, 7, 9, 9, 6, 9, 2, 5],
       [2, 2, 1, 3, 1, 8, 7, 5],
       [4, 6, 5, 4, 9, 3, 4, 3],
       [1, 3, 3, 5, 4, 0, 1, 4]])

In [146]:
np.random.randint(10, size = (4,8,3))  

array([[[9, 8, 0],
        [1, 8, 0],
        [0, 0, 6],
        [3, 5, 2],
        [0, 4, 7],
        [2, 4, 1],
        [2, 3, 3],
        [7, 8, 6]],

       [[0, 6, 1],
        [7, 2, 8],
        [2, 6, 8],
        [5, 7, 9],
        [2, 3, 5],
        [2, 2, 6],
        [9, 3, 6],
        [5, 8, 4]],

       [[5, 4, 5],
        [9, 0, 7],
        [2, 7, 6],
        [3, 7, 3],
        [9, 2, 4],
        [1, 6, 7],
        [1, 5, 2],
        [6, 5, 7]],

       [[4, 2, 3],
        [4, 8, 0],
        [8, 3, 4],
        [2, 8, 2],
        [0, 5, 8],
        [3, 6, 0],
        [7, 7, 1],
        [6, 7, 6]]])

# Index ile Elemanlara Erişmek

In [2]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([0, 8, 1, 8, 4, 8, 5, 6, 2, 4])

In [3]:
a[0]

0

In [4]:
a[-1]  #tersten elemana erismek

4

In [7]:
a[0] = 100   #ilk index'e eleman etama

In [8]:
a

array([100,   8,   1,   8,   4,   8,   5,   6,   2,   4])

In [9]:
m = np.random.randint(10, size = (3,5))
m

array([[6, 1, 5, 8, 7],
       [7, 7, 9, 9, 3],
       [4, 1, 8, 3, 2]])

In [12]:
m[0,0]  #sifirinci satir, birinci sutun

6

In [13]:
m[1,1] #birinci satir, birinci sutun

7

In [14]:
m[1, 4] # birinci satir, dorduncu sutun

3

In [15]:
m[1,4] = 99 # birinci satir, dorduncu sutun elemanina 99 degerini atama

In [16]:
m

array([[ 6,  1,  5,  8,  7],
       [ 7,  7,  9,  9, 99],
       [ 4,  1,  8,  3,  2]])

In [19]:
m[1,3] = 2.2 # birinci satir, dorduncu sutun elemanina 2.2 degerini atama, ondalikli olarak deger atamasi kabul edilmeyecek

In [20]:
m

array([[ 6,  1,  5,  8,  7],
       [ 7,  7,  9,  2, 99],
       [ 4,  1,  8,  3,  2]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümeine Erişmek) 

In [21]:
import numpy as np

In [22]:
a = np.arange(20,30) # tek boyutlu bir array
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
a[0:3]  # silicing islemi (:) araya birakarak bir cesit dilimleme, ayirma islemidir, su elemandan su elemana kadar git demek , aralikli secme

array([20, 21, 22])

In [26]:
a[:3]

array([20, 21, 22])

In [28]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [30]:
a[1::2]  # ikiser ikiser olarak git 

array([21, 23, 25, 27, 29])

In [31]:
a[0::2]

array([20, 22, 24, 26, 28])

In [34]:
a[0::2]

array([20, 22, 24, 26, 28])

In [36]:
a[2::2]

array([22, 24, 26, 28])

In [37]:
a[0::3] # # sifirinci index'ten 3'er 3'er ilerle

array([20, 23, 26, 29])

In [38]:
#iki boyutlu slice islemleri

In [41]:
m = np.random.randint(10, size = (5,5))  # boyut 5X5 bir matris olusturulur

In [42]:
m

array([[3, 7, 2, 5, 6],
       [9, 0, 2, 0, 3],
       [8, 7, 5, 7, 8],
       [8, 7, 9, 7, 7],
       [3, 3, 0, 9, 8]])

In [43]:
m[:,0]  # tum satirlari sec (:) , 0 inci sutundaki

array([3, 9, 8, 8, 3])

In [44]:
m[:,1]  # tum satirlari sec (:) , 1 inci sutundaki

array([7, 0, 7, 7, 3])

In [46]:
m[:,4]  # tum satirlari sec(:), 4 uncu index nolu stundaki elemanlar

array([6, 3, 8, 7, 8])

In [48]:
m[0,:] # sifirinci satirdaki tum sutunlar

array([3, 7, 2, 5, 6])

In [49]:
m[1,:] # birinci satirdaki tum sutunlar

array([9, 0, 2, 0, 3])

In [50]:
m[0:2, 0:3]  # sifirdan 2'ye kadar tum satirlar ve sifirdan 3'e kadar tum sutunlari al

array([[3, 7, 2],
       [9, 0, 2]])

In [53]:
m[0:3, 0:3]  # sifirdan 3'e kadar tum satirlar ve sifirdan 3'e kadar tum sutunlari al

array([[3, 7, 2],
       [9, 0, 2],
       [8, 7, 5]])

In [54]:
m[:,:2] # tum satirlar ve 2. index'e kadar  olan tum sutunlar

array([[3, 7],
       [9, 0],
       [8, 7],
       [8, 7],
       [3, 3]])

In [55]:
m[:,0:2] # tum satirlar ve 2. index'e kadar  olan tum sutunlar, ustteki satirla ayni isi gorur, 

array([[3, 7],
       [9, 0],
       [8, 7],
       [8, 7],
       [3, 3]])

In [57]:
m  # tum satir ve sutunlar

array([[3, 7, 2, 5, 6],
       [9, 0, 2, 0, 3],
       [8, 7, 5, 7, 8],
       [8, 7, 9, 7, 7],
       [3, 3, 0, 9, 8]])

# Alt Kume Üzerinde İşlem Yapmak (operate on a subset)

In [199]:
import numpy as np
a = np.random.randint(10, size = (5,5))
a

array([[0, 2, 1, 8, 0],
       [5, 9, 9, 4, 3],
       [1, 8, 5, 4, 9],
       [2, 0, 7, 7, 4],
       [5, 9, 8, 1, 1]])

In [59]:
alt_a = a[0:3, 0:2]     # alt kume
alt_a

array([[6, 8],
       [5, 2],
       [6, 0]])

In [62]:
alt_a[0,0] = 9999    # bu tarz atamalar ana kumeyi etkiler, bunu etkilememesi icin coppy() kullanip, bagimzis alt kume olusturmali
alt_a[1,1] = 888

In [63]:
alt_a

array([[9999,    8],
       [   5,  888],
       [   6,    0]])

In [69]:
alt_b = a[0:3, 0:2].copy()  # copy() ile ana kumeden bagimsiz bir alt kume olusturup uzerinde calismak gerekir
alt_b

array([[9999,    8],
       [   5,  888],
       [   6,    0]])

In [66]:
alt_b[0,0] = 1111
alt_b[1,1] = 2222
alt_b

array([[1111,    8],
       [   5, 2222],
       [   6,    0]])

In [200]:
a

array([[0, 2, 1, 8, 0],
       [5, 9, 9, 4, 3],
       [1, 8, 5, 4, 9],
       [2, 0, 7, 7, 4],
       [5, 9, 8, 1, 1]])

In [209]:
a[0:,[1,2,3]]

array([[2, 1, 8],
       [9, 9, 4],
       [8, 5, 4],
       [0, 7, 7],
       [9, 8, 1]])

In [210]:
a[0,[1,2,3]]

array([2, 1, 8])

# Fancy Index ile Elemanlara Erişmek
### Fancy (büyüleyici, Fantastik) pandas ve numpy arraylerinde daha ileri düzeyde eleman seçmede bize yardımcı olacak
### en önemli kavramdır

In [71]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [72]:
v[1]

3

In [73]:
v[3]

9

In [75]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [76]:
al_getir = [1,3,5]

In [77]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [80]:
v[al_getir]  # fancy index ile gerceklesti, kozeli oparantez kullanilir

array([ 3,  9, 15])

In [81]:
#iki boyutta fancy

In [82]:
m = np.arange(9).reshape((3,3))

In [83]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [88]:
m[satir,sutun]

array([1, 5])

In [89]:
#basit index ile fancy index

In [90]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
m[0, [1,2]]   # klasik index

array([1, 2])

In [95]:
#slice ile fancy

In [96]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [97]:
# Koşullu Eleman İşlemleri

In [98]:
import numpy as np
v = np.array([1,2,3,4,5])

In [99]:
v > 5 

array([False, False, False, False, False])

In [100]:
v < 3

array([ True,  True, False, False, False])

In [114]:
v[v < 3]  # fancy ile sorgu sonucu elde edilen elemenalari getir, fancy arka planda calisir

array([1, 2])

In [115]:
v[ v > 3]

array([4, 5])

In [116]:
v[ v >= 3]

array([3, 4, 5])

In [117]:
v[ v <= 3]

array([1, 2, 3])

In [118]:
v[ v == 3] # esit olanlari getir

array([3])

In [119]:
v[v != 3]  # 3'un disinda kalanlari getir

array([1, 2, 4, 5])

In [120]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [121]:
v * 5

array([ 5, 10, 15, 20, 25])

In [122]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [123]:
v**2 # kare alma islemleri

array([ 1,  4,  9, 16, 25], dtype=int32)

# Matematiksel İşlemler

In [128]:
import numpy as np
v = np.array([1,2,3,4,5])

In [129]:
v - 1

array([0, 1, 2, 3, 4])

In [130]:
v * 5

array([ 5, 10, 15, 20, 25])

In [131]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [132]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [133]:
#ufunc kavrami

In [135]:
np.subtract(v , 1) # tum elemanlardan 1 cikar 

array([0, 1, 2, 3, 4])

In [136]:
np.add(v, 1) # her bir elemana 1 ekle

array([2, 3, 4, 5, 6])

In [138]:
np.divide(v, 3) # her bir elemani bol

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [139]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [142]:
np.power(v,3) # bir elemamin kuvvetini almak

array([  1,   8,  27,  64, 125], dtype=int32)

In [144]:
np.mod(v,2) # mod islemi uygulanir, 2'ye bolumunden kalanlar getirilir (v % 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [146]:
np.absolute(np.array([-3])) # mutlak deger almak

array([3])

In [148]:
np.sin(360)

0.9589157234143065

In [159]:
np.cos(180)

-0.5984600690578582

In [160]:
np.tan(120)

0.7131230097859091

In [161]:
v = np.array([1,2,3])

In [162]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [163]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [164]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [165]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\anaconda\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\anaconda\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-

In [166]:
#cheatsheet      aranilan kavramin sonuna yazilip google da aratilirsa daha derli toplu dokuman elde edilir


# İstatistiksel Hesaplamalar

In [ ]:
np.mean(arr,axis=0) | Returns mean along specific axis 
arr.sum() | Returns sum of arr 
arr.min() | Returns minimum value of arr 
arr.max(axis=0) | Returns maximum value of specific axis 
np.var(arr) | Returns the variance of array 
np.std(arr,axis=1) | Returns the standard deviation of specific axis 
arr.corrcoef() | Returns correlation coefficient of array


In [167]:
v

array([1, 2, 3])

In [168]:
np.mean(v, axis=0) 

2.0

In [169]:
v.sum()

6

In [170]:
v.min()

1

In [171]:
v.max(axis=0)

3

In [172]:
np.var(v)

0.6666666666666666

In [175]:
np.std(v, axis=0)

0.816496580927726

# NumPy ile iki Bilinmeyenli Denklem Çözümü

In [176]:
import numpy as np

##### 5*x0 + x1 = 12
##### x0 + 3 *x1 = 10 

In [181]:
a = np.array([[5,1], [1,3]]) # denklemlerin katsayilari bir vektore yazilir
b = np.array([12,10]) # denklem sonuclarinin yer aldigi diger vektor

In [182]:
a

array([[5, 1],
       [1, 3]])

In [183]:
b

array([12, 10])

In [186]:
x = np.linalg.solve(a,b) #birinci ve ikinci arguman arasinda olusacak hesaplama neticesindeki denklem katsayilarini hesapla

In [187]:
x

array([1.85714286, 2.71428571])

In [1]:
import numpy as np
v = np.array([7, 3, 4, 7, 0, 9, 3, 2, 9, 2])
v[-4]

3

# Pandas Serisi Oluşturmak

In [3]:
import pandas as pd

In [4]:
seri = pd.Series([13,29,83,4,5])

In [5]:
type(seri)

pandas.core.series.Series

In [6]:
seri.axes  # bu serinin index bilgilerine ulasabiliriz

[RangeIndex(start=0, stop=5, step=1)]

In [7]:
seri.dtype # seride ki degerler ile ilgili bilgi almak icin

dtype('int64')

In [8]:
seri.size #seri hakkındaki eleman sayısını verir

5

In [9]:
seri.ndim #seri hakkındaki boyut hakknda bilgi verir , kaç boyutlu olduğu bilgisini verir

1

In [10]:
seri.values  # bir numpy arayi seklinde erismek istersem , yani bir vektor erisim icin olarak VALUES kavrami kullanilir

array([13, 29, 83,  4,  5], dtype=int64)

In [11]:
seri.head() # serinin tüm argümanlarina bastan erismek icin kullanilir

0    13
1    29
2    83
3     4
4     5
dtype: int64

In [12]:
seri.head(3) # serinin ilgili argümanlarina erismek icin kullanilir, ilk uc arguman

0    13
1    29
2    83
dtype: int64

In [14]:
seri.tail() # serinin tüm argümanlarina sondan erismek icin kullanilir

0    13
1    29
2    83
3     4
4     5
dtype: int64

In [16]:
seri.tail(2) # serinin ilgili argümanlarina sondan erismek icin kullanilir, son iki eleman

3    4
4    5
dtype: int64

# Pandas Serisi Oluşturmak

In [6]:
import pandas as pd

In [7]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [ ]:
#index isimlendirmesi

In [10]:
seri = pd.Series([10,88,3,4,5])

In [11]:
type(seri)

pandas.core.series.Series

In [14]:
pd.Series([99,22,332,94,5]) # varsayılan indexleme, sıfırdan başlar

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [15]:
pd.Series([99,22,332,94,5], index = [2,3,4,5,6]) # indexlemeyi kendimizde yapabliriz

2     99
3     22
4    332
5     94
6      5
dtype: int64

In [19]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"]) # indexlemeyi kendimizde yapabliriz

In [20]:
seri["a"]

99

In [21]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [22]:
#sozluk üzerinden liste oluşturmak

In [23]:
sozluk = {"reg":10, "log":11, "cart":12}

In [24]:
seri = pd.Series(sozluk)

In [25]:
seri

reg     10
log     11
cart    12
dtype: int64